# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stage_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1092, 535)
        Form.setStyleSheet("background:rgb(30,30,30);\n"
"")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_Stages = QtWidgets.QWidget(Form)
        self.widget_Stages.setStyleSheet("")
        self.widget_Stages.setObjectName("widget_Stages")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_Stages)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_Stages)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.widget_Stages)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_numerador = QtWidgets.QLabel(self.widget_Stages)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_numerador.setFont(font)
        self.label_numerador.setStyleSheet("color:white")
        self.label_numerador.setText("")
        self.label_numerador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_numerador.setObjectName("label_numerador")
        self.verticalLayout.addWidget(self.label_numerador)
        self.line_ecuacion = QtWidgets.QFrame(self.widget_Stages)
        self.line_ecuacion.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_ecuacion.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_ecuacion.setObjectName("line_ecuacion")
        self.verticalLayout.addWidget(self.line_ecuacion)
        self.label_denominador = QtWidgets.QLabel(self.widget_Stages)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_denominador.setFont(font)
        self.label_denominador.setStyleSheet("color:white")
        self.label_denominador.setText("")
        self.label_denominador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_denominador.setObjectName("label_denominador")
        self.verticalLayout.addWidget(self.label_denominador)
        self.line_ecuacion_2 = QtWidgets.QFrame(self.widget_Stages)
        self.line_ecuacion_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_ecuacion_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_ecuacion_2.setObjectName("line_ecuacion_2")
        self.verticalLayout.addWidget(self.line_ecuacion_2)
        self.line_ecuacion_3 = QtWidgets.QFrame(self.widget_Stages)
        self.line_ecuacion_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_ecuacion_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_ecuacion_3.setObjectName("line_ecuacion_3")
        self.verticalLayout.addWidget(self.line_ecuacion_3)
        self.label_n = QtWidgets.QLabel(self.widget_Stages)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_n.setFont(font)
        self.label_n.setStyleSheet("color:white")
        self.label_n.setText("")
        self.label_n.setAlignment(QtCore.Qt.AlignCenter)
        self.label_n.setObjectName("label_n")
        self.verticalLayout.addWidget(self.label_n)
        self.label_q = QtWidgets.QLabel(self.widget_Stages)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_q.setFont(font)
        self.label_q.setStyleSheet("color:white")
        self.label_q.setText("")
        self.label_q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q.setObjectName("label_q")
        self.verticalLayout.addWidget(self.label_q)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.widget_Stages)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Stage 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
